SET search_path TO public;

CREATE TABLE permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission VARCHAR(60) NOT NULL UNIQUE
);

INSERT INTO permissions (permission) VALUES
  ('list_resources'),
  ('read_resource'),
  ('create_resource'),
  ('update_resource'),
  ('delete_resource');