package main

import (
	"github.com/bencoronard/demo-go-bff-web/internal/config"
	"github.com/bencoronard/demo-go-bff-web/internal/permission"
	"github.com/bencoronard/demo-go-bff-web/internal/token"
	"github.com/bencoronard/demo-go-common-libs/actuator"
	"github.com/bencoronard/demo-go-common-libs/http"
	"github.com/bencoronard/demo-go-common-libs/jwt"
	"github.com/bencoronard/demo-go-common-libs/logger"
	"github.com/bencoronard/demo-go-common-libs/otel"
	"github.com/bencoronard/demo-go-common-libs/rdb"
	"github.com/bencoronard/demo-go-common-libs/server"
	"github.com/bencoronard/demo-go-common-libs/validator"
	"github.com/bencoronard/demo-go-common-libs/vault"
	"go.uber.org/fx"
)

func main() {
	fx.New(
		fx.Provide(
			logger.NewStdOutLogger,
			vault.NewClient,
		),
		fx.Provide(
			config.NewProperties,
		),
		fx.Provide(
			rdb.NewPgDriver,
			rdb.NewDB,
			fx.Annotate(
				rdb.NewHealthChecker,
				fx.ResultTags(`group:"healthcheck"`),
			),
		),
		fx.Provide(
			jwt.NewAsymmIssuer,
			validator.New,
		),
		fx.Provide(
			permission.NewPermissionRepo,
			token.NewTokenService,
			token.NewTokenHandler,
		),
		fx.Provide(
			otel.NewResource,
			otel.NewPropagator,
			otel.NewTracerProvider,
			otel.NewMeterProvider,
			otel.NewLoggerProvider,
		),
		fx.Provide(
			http.NewGlobalErrorHandler,
			http.NewEchoRouter,
			config.NewHttpServer,
		),
		fx.Invoke(
			actuator.New,
			server.ServeHTTP,
		),
	).Run()
}
